---
- hosts: all
  become: yes
  vars:
    grafana_version: 8.3.3
  tasks:
    - name: Add Grafana's official GPG key
      apt_key:
        url: "https://packages.grafana.com/gpg.key"
        state: present

    - name: Add Grafana's official APT repository
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present
          
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Grafana
      apt:
        name: grafana
        state: latest
