version: '3'

services:
  zookeeper:
    image: zookeeper:latest
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
    volumes:
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog
    networks:
      - kafka

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - kafka
    labels:
      - traefik.enable=true
      - traefik.http.routers.kafka.rule=Host(`kafka.yourdomain.com`)
      - traefik.http.services.kafka.loadbalancer.server.port=9092
      - traefik.http.routers.kafka.tls.certresolver=myresolver
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  zookeeper_data:
  zookeeper_datalog:
  kafka_data:

networks:
  kafka:
