version: '3.7'

services:
  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
      - /var/log/mongodb:/var/log/mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mysecretpassword
    networks:
      - proxy

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - proxy
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: myuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: mysecretpassword
      VIRTUAL_HOST: mongoexpress.mywebsite.com
      LETSENCRYPT_HOST: mongoexpress.mywebsite.com
      LETSENCRYPT_EMAIL: myemail@mywebsite.com

networks:
  proxy:
    external: true

volumes:
  mongo_data: {}
